---
build_from:
  aarch64: ghcr.io/hassio-addons/base-python:16.1.0
  amd64: ghcr.io/hassio-addons/base-python:16.1.0
  armhf: ghcr.io/hassio-addons/base-python:16.1.0
  armv7: ghcr.io/hassio-addons/base-python:16.1.0
  i386: ghcr.io/hassio-addons/base-python:16.1.0
codenotary:
  base_image: notary@home-assistant.io
  signer: notary@home-assistant.io
  
  
