---
build_from:
  aarch64: homeassistant/aarch64-base-python:latest
  amd64: homeassistant/amd64-base-python:latest
  armhf: homeassistant/armhf-base-python:latest
  armv7: homeassistant/armv7-base-python:latest
  i386: homeassistant/i386-base-python:latest
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev